# Generated by Django 2.2.5 on 2019-09-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mytable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytable',
            old_name='field1',
            new_name='ID',
        ),
    ]
